Models/Domain/MenuItem.cs
using System.ComponentModel.DataAnnotations;

namespace Ordering_App.Models.Domain
{
    public class MenuItem
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public required string Name { get; set; }
        public required string Description { get; set; }
        [Range(0.01, 1000, ErrorMessage = "Price must more than R 0.00")]
        public decimal Price { get; set; }
        //
        public Restaurant? Restaurant { get; set; }
        public List<OrderItem>? OrderItems { get; set; }

    }
}

Controllers/MenuItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Ordering_App.Interfaces;
using Ordering_App.Models;
using Ordering_App.Models.DTOs;
using Ordering_App.Repositories;

namespace Ordering_App.Controllers
{
    public class MenuItemController : Controller
    {
        private readonly IMenuItemRepository menuItemRepository;

        public MenuItemController(IMenuItemRepository menuItemRepository)
        {
            this.menuItemRepository = menuItemRepository;
        }
        [HttpGet]
        public async Task<IActionResult> MenuItems([FromQuery] UserParams userParams
            , decimal minPrice, decimal maxPrice, string restaurantName, string memuItemName)
        {
            if (minPrice >= 0) userParams.MinPrice = minPrice;
            if (maxPrice != 0 && maxPrice != userParams.MaxPrice) userParams.MaxPrice = maxPrice;
            userParams.PageSize = 1;
            if (!restaurantName.IsNullOrEmpty())
            {
                userParams.RestaurantName = restaurantName;
            }
            var items = await menuItemRepository.GetAllAsync(userParams);
            ViewBag.TotalCount = items.TotalCount;
            ViewBag.TotalPages = items.TotalPages;
            ViewBag.CurrentPage = userParams.PageNumber;
            ViewBag.MinPrice = userParams.MinPrice;
            ViewBag.MaxPrice = userParams.MaxPrice;
            ViewBag.RestaurantName = userParams.RestaurantName;
            ViewBag.MemuItemName = memuItemName;
            return View(items);
        }
        public IActionResult AddMenuItem(int id)
        {
            TempData["RestaurantId"] = id;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddMenuItem(AddMenuItemDTO addMenuItemDTO, int id)
        {
            var menuITemDM = await menuItemRepository.CreateAsync(addMenuItemDTO);
            menuITemDM.RestaurantId = id;
            string errorMessage ="",successMessage = "";
            if (await menuItemRepository.ItemExistsAsync(menuITemDM))
            {
                errorMessage = $"{menuITemDM.Name.ToUpper()} at {menuITemDM.Restaurant!.Name!} allready exists.";
            }
            
            if (await menuItemRepository.SaveAllAsync())
            {
                successMessage = $"{addMenuItemDTO.Name.ToUpper()} has been successful created.";
            }
            TempData["Error"] = errorMessage;
            TempData["Success"] = successMessage;
            return View();
        }
        
    }
}

Controllers/RestaurantController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Ordering_App.Interfaces;
using Ordering_App.Models;
using Ordering_App.Models.Domain;
using Ordering_App.Models.DTOs;
using Ordering_App.Repositories;

namespace Ordering_App.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly IRestaurantRepository restaurantRepository;
        private readonly IMapper mapper;

        public RestaurantController(IRestaurantRepository restaurantRepository, IMapper mapper)
        {
            this.restaurantRepository = restaurantRepository;
            this.mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> Restaurants([FromQuery] UserParams userParams)
        {
            userParams.PageSize = 1;
            var restaurants = await restaurantRepository.GetAllAsync(userParams);
            ViewBag.TotalPages = restaurants.TotalPages;
            ViewBag.CurrentPage = userParams.PageNumber;
            return View(restaurants);
        }
        public IActionResult AddRestaurant()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRestaurant(AddRestaurantDTO addRestaurantDTO)
        {
            string errorMessage ="",successMessage = "";
            if (await restaurantRepository.RestaurantExistsAsync(addRestaurantDTO))
            {
                errorMessage = $"{addRestaurantDTO.Name.ToUpper()} at {addRestaurantDTO.LocationDescription} allready exists.";
            }
            else
            {
                await restaurantRepository.CreateAsync(addRestaurantDTO);
                if (await restaurantRepository.SaveAllAsync())
                {
                    successMessage = $"{addRestaurantDTO.Name.ToUpper()} has been successful created.";
                }
            }
            TempData["Error"] = errorMessage;
            TempData["Success"] = successMessage;
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> RestaurantsDetails(int id, [FromQuery] UserParams userParams
        ,string menuItemName,decimal minPrice, decimal maxPrice, string menuItemDescription)
        {
            // var items = await restaurantRepository.GetByIdAsync(id);
            // return View(items);
            
            var restaurants = await restaurantRepository.GetPagedByIdAsync(userParams, id);
            var restaurant = restaurants.FirstOrDefault();

            var filteredItems = restaurant.MenuItems.AsQueryable();

            if (!string.IsNullOrEmpty(userParams.MenuItemName))
                filteredItems = filteredItems.Where(m => m.Name.ToLower().Contains(userParams.MenuItemName.ToLower()));

            if (!string.IsNullOrEmpty(userParams.MenuItemDescription))
                filteredItems = filteredItems.Where(m => m.Description.ToLower().Contains(userParams.MenuItemDescription.ToLower()));

            if (userParams.MinPrice > 0)
                filteredItems = filteredItems.Where(m => m.Price >= userParams.MinPrice);

            if (userParams.MaxPrice < decimal.MaxValue)
                filteredItems = filteredItems.Where(m => m.Price <= userParams.MaxPrice);

            // Overwrite items in the restaurant
            restaurant.MenuItems = filteredItems.ToList();

            ViewBag.TotalCount = restaurants.TotalCount;
            ViewBag.TotalPages = restaurants.TotalPages;
            ViewBag.CurrentPage = userParams.PageNumber;
            ViewBag.MinPrice = userParams.MinPrice;
            ViewBag.MaxPrice = userParams.MaxPrice;
            ViewBag.Description = userParams.MenuItemDescription;
            ViewBag.ItemName = userParams.MenuItemName;
            
            return View(restaurant);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var restaurant = await restaurantRepository.GetByIdAsync(id);
            if (restaurant == null)
            {
                TempData["Error"] = "Restaurant not found";
                return RedirectToAction("Restaurants");
            }
            return View(restaurant);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Restaurant restaurant)
        {
            string errorMessage = "", successMessage = "";
            if (restaurant == null)
            {
                errorMessage = "Restaurant cannot be found";
            }
            else
            {
                await restaurantRepository.UpdateAsync(restaurant);
                if (await restaurantRepository.SaveAllAsync())
                {
                    successMessage = "Restaurant has been edited successfully";
                }
            }
            TempData["Error"] = errorMessage;
            TempData["Success"] = successMessage;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            string errorMessage = "", successMessage = "";
            var restaurant = await restaurantRepository.GetByIdAsync(id);
            if (restaurant == null)
            {
                errorMessage = "Restaurant cannot be found";
            }
            else
            {
                await restaurantRepository.DeleteAsync(restaurant);
                if (await restaurantRepository.SaveAllAsync())
                {
                    successMessage = "Restaurant has been successfully deleted";
                }
                else
                {
                    errorMessage = "Something happened";
                }
            }
            TempData["Error"] = errorMessage;
            TempData["Success"] = successMessage;
            return RedirectToAction("Restaurants");
        }

    }
}

Views/MenuItem/AddMenuItem.cshtml
@using Ordering_App.Models.DTOs
@model AddMenuItemDTO

@{
    var id = TempData["RestaurantId"];
}

@if (TempData["Success"] != "" && TempData["Success"] != null)
{
    <div class="overlay-alert">
        @await Html.PartialAsync("_SuccessAlert", new AlertModel {
        Message = TempData["Success"]!.ToString(),
        IsDivDisplayed = TempData["Success"] != "" && TempData["Success"] != null,
        RedirectUrl = Url.Action("Restaurants", "Restaurant")
        })
</div>
}

@if (TempData["Error"] != "" && TempData["Error"] != null)
{
    <div class="overlay-alert">
        @await Html.PartialAsync("_ErrorAlert", new AlertModel {
        Message = TempData["Error"]!.ToString(),
        IsDivDisplayed = TempData["Error"] != "" && TempData["Error"] != null,
        RedirectUrl = Url.Action("AddMenuItem", "MenuItem")
        })
</div>
}
<div class="card mt-4 small-box">
    <div class="card-header heading-form">
        <p>Add New Item</p>
    </div>
    <div class="card-body p-4">
        <form method="post" asp-action="AddMenuItem" asp-controller="MenuItem">
            <input value="@id" name="id" hidden>
            <div class="row">
                <div class="mb-3 col-md-12">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="XXXX XXXX XXXX" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-md-12">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" placeholder="XXXX XXXX XXXX"
                        required />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-md-12">
                    <label asp-for="Price"></label>
                    <input asp-for="Price" class="form-control" type="number"
                        required />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <a href="/Restaurant/Restaurants" class=" btn btn-success w-100"><i
                            class="bi bi-arrow-left-square w-100">
                        </i> Go Back</a>
                </div>
                <div class="col-6">
                    <button class="btn btn-success w-100" type="submit"><i class="bi bi-save"></i> Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/MenuItem/MenuItems.cshtml
@using Ordering_App.Models.Domain
@model IEnumerable<MenuItem>

<div class="container-fluid" style="background-color: rgb(241, 234, 234);border-radius: 0.6rem;">
	@* <div class="row">
		<div class="col-12 mt-3">
			<a class="btn btn-info" href="/Employee/AddEmployee">
				<i class="bi bi-person-fill-add text-secondary"></i> Add New Employee
			</a>
		</div>
	</div> *@
	<!--Filters section-->
	<div class="row">
		<div class="col-12 mt-3">
			<form asp-action="MenuItems" asp-controller="MenuItem" method="get">
				<!--Balance and LastDepositMonth Filters-->
				<div class="row g-1 mb-3">
					<!--Price From-->
					<div class="col-6 col-sm-4 col-md-3 col-lg-2">
						<label class="form-label">Price from:</label>
						<input type="number" class="form-control" style="width: 6rem" name="minPrice"
							   value="@ViewBag.MinPrice" />
					</div>
					<!--Price To-->
					<div class="col-6 col-sm-4 col-md-3 col-lg-2">
						<label class="form-label">Price to:</label>
						<input type="number" class="form-control" style="width: 7rem" name="maxPrice"
							   value="@ViewBag.MaxPrice" />
					</div>
					<!-- Restaurant Name-->
					<div class="col-6 col-sm-6 col-md-3 col-lg-2 d-flex flex-column">
						<label class="form-label">Restaurant Name</label>
						<input type="month" class="form-control" style="width: 10.5rem"
							   value="@ViewBag.RestaurantName" name="restaurantName" />
					</div>
					<!--Action Buttons-->
					<div class="col-12 col-md-6 col-lg-6">
						<label class="form-label d-done d-md-block">&nbsp;</label>
						<div class="d-flex flex-wrap gap-1">
							<button class="btn btn-primary" type="submit">
								<i class="bi bi-send-check-fill text-dark"></i> Apply filters
							</button>
							<a href="/Employee/Employees" class="btn btn-info" type="button">
								<i class="bi bi-arrow-clockwise text-success"></i> Reset filters
							</a>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Total Employees Found: @ViewBag.TotalCount</th>
				</tr>
				<tr>
					<th>Name</th>
					<th>Price (R)</th>
					<th>Description</th>
					<th>Options</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>@item.Name</td>
						<td>@item.Price</td>
						<td>@item.Description</td>
						<td>
							<div class="hover-btn">
								<a class="btn" asp-action="Edit" asp-asp-controller="MenuItem"
								   asp-route-id="@item.Id">
									<i class="bi bi-info-circle text-info"></i>
								</a>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
	<div class="row mt-3">
		<div class="col-12 d-flex justify-content-center">
			<nav aria-label="Page navigation"></nav>
			<ul class="pagination justify-content-center">
				<li class="page-item @(ViewBag.CurrentPage == 1 ? "disabled" : "")">
					<a class="page-link" asp-action="MenuItems" asp-route-pageNumber="@(ViewBag.CurrentPage - 1)"
					   asp-route-minPrice="@ViewBag.MinPrice" asp-route-maxPrice="@ViewBag.MaxPrice"
					   style="width:5rem;">Previous</a>
				</li>

				@for (int i = 1; i <= ViewBag.TotalPages; i++)
				{
					<li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")">
						@if (i <= 2)
						{
							<a class="page-link" asp-action="MenuItems" asp-route-pageNumber="@i"
							   asp-route-minPrice="@ViewBag.MinPrice" asp-route-maxPrice="@ViewBag.MaxPrice">
								@i
							</a>
						}
					</li>
				}

				<li class="page-item @(ViewBag.CurrentPage == ViewBag.TotalPages ? "disabled" : "")">
					<a class="page-link" asp-action="MenuItems" asp-route-pageNumber="@(ViewBag.CurrentPage + 1)"
					   asp-route-minPrice="@ViewBag.MinPrice" asp-route-maxPrice="@ViewBag.MaxPrice"
					   style="width:5rem;">
						Next
					</a>
				</li>
			</ul>
			</nav>
		</div>
	</div>

</div>